Repository GDSC-NITH/Cookbook-2-Hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#2 Created react docum
  Web-development/Reactjs/ReactRouter.md
  Web-development/Reactjs/component.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#3 Create tailwind.md
  Web-development/Tailwind CSS/tailwind.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#4 Create Css-flexbox.md
  Web-development/Css-flexbox.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#1 dijsktra algorithm
  Graph/Dijsktra.md
  open_cv/object_tracking.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#7 Create EJS.md
  Web-development/EJS.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#8 Create nodeJS.md
  Web-development/nodeJS.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#15 Create Java.md
  Java/Java.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#6 Create DataTypes.md
  CPP/DataTypes.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#21 Kotlin
  Kotlin Android/XML Vs JetpackCompose.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#9 Design Sprint Added
  UI-UX Design/DesignSprint.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#18 React JSX
  Web-development/Reactjs/ReactJSX.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#25 Create django-rest-framework.md
  Web-development/django-rest-framework/django-rest-framework.md
Labels: Hacktoberfest, Hacksquad

#20 Update Java.md
  Java/Java.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#19 Create javascript.md
  Web-development/JavaScript.md
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted

#24 Android Layout (Kotlin)
  Kotlin Android/Layouts/layouts_android.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#22 DP vs SP Kotlin
  Kotlin Android/dp_sp_android.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#27 Create Basics.md
  Data Structure/Priority Queue/data-structure.md
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted

#28 linked_list.md
  Data Structure/Priority Queue/linked_list.md
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted

#30 Complexities
  Data Structure/Priority Queue/Complexities.md
Labels: documentation, Hacktoberfest, Hacktoberfest-accepted

#29 tree.md
  Data Structure/Priority Queue/Queue.md
Labels: enhancement, Hacktoberfest, Hacktoberfest-accepted

#37 Create TIMECOMPLEXITY.md
  CPP/TIMECOMPLEXITY.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#39 Create vector.md
  CPP/vector.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#40 Create TIMECOMPLEXITY.md
  CPP/TIMECOMPLEXITY.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#41 Create bst.md
  CPP/bst.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#42 Create HashTable.md
  Data Structure/Priority Queue/HashTable.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#43 Create linkedlist.md
  Data Structure/Priority Queue/linkedlist.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#45 Create stack.md
  Data Structure/Priority Queue/stack.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#46 flutter
  Flutter/create_first_app.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#47 space-complexity
  CPP/space_complexity.md
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted

#50 Added ArrayList.md
  Java/ArrayList.md
  Java/Bubblesort.md
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted

#55 Scaffold widget added
  Flutter/Scaffold/scaffold_widget.md
  Kotlin Android/Jetpack Compose/Basic Layouts/basic_layouts.md
Labels: Hacktoberfest, Hacktoberfest-accepted
